### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by haraldschilly** [conery/nbscan#1]
This misses a `setup.py` file, such that it can be installed via pip. You don't really need to bother with PyPi right now in this state, i.e. the initial goal should be that just `pip install git+https://github.com/conery/nbscan.git` works.

**Comment by conery** [comment]
Hi Harald --

Thanks for the tip!  

JC

**Comment by williamstein** [comment]
> You don't really need to bother with PyPi right now in this state

That said, PyPi is **really** easy to use and get going with.
